- id: djangofmt
  name: Djangofmt
  description: "A fast, HTML aware, Django template formatter, written in Rust"
  entry: djangofmt
  language: python
  types_or: [html, jinja]
  require_serial: true
  minimum_pre_commit_version: "2.9"

- id: djangofmt-svg
  name: Djangofmt (svg)
  description: "A fast, HTML aware, Django template formatter, written in Rust"
  entry: djangofmt
  language: python
  types: [svg]
  require_serial: true
  minimum_pre_commit_version: "2.9"
